# Performance

## Reviews
There should be informal reviews at every weekly meeting.
The point is mutual feedback, i.e., we can discuss your progress and develop achievable goals for the next few days to years, and you can tell me if there are areas in which I can provide better help.
If you would like more formal progress reviews, let me know.
Please also let me know if you are ever worried about your progress.
Postdocs and salaried researchers will get formal annual reviews as required by the Biological Sciences Division, but they are really secondary to the regular meetings (i.e., there should be no surprises).

## My commitments

* Meet with you at least biweekly (usually weekly) to discuss research and professional opportunities.
* Help give you an accelerated introduction to the field.
* Provide rapid (within days) critical feedback on research ideas and drafts---*with advance notice!*
* Help you establish relationships with other scientists in field.
* Promote your work in conferences and meetings.
* Help you attend conferences and meetings.
* Help identify areas of professional growth.
* Provide teaching and mentoring opportunities, if desired.
* Fund you for at least $n$ years (as agreed), assuming steady progress.
* Be a trustworthy, reliable, honest, hard-working, constructive, respectful, and communicative colleague.
* (For postdocs) Help you identify a line of research to continue when you leave the lab.

## Universal expectations

* Follow the lab's principles (Section \@ref(principles)) and all our described work practices, including the project management and programming techniques described in Section \@ref(so-you-wanna).
* Take full intellectual ownership of your research, i.e., think hard about whether you and your collaborators are doing the right thing, search for relevant papers, and push your projects forward at a good pace. 
* Respect restrictions on data usage and information sharing. 
The lab conducts "human subjects research" (in that we work with data from individual humans) and often works with protected health information (PHI) and limited data sets (LDS). 
Lab members need to be aware of what PHI looks like so they can report its possible misuse. 
For instance, files containing PHI may accidentally be stored on the wrong machine, or another research group might accidentally share PHI or the wrong PHI.
The CIVIC and CEIRR consortia to which we belong have non-disclosure agreements prohibiting sharing of information (results, comments, etc.) from meetings.
When in doubt, be cautious and ask about data sharing, results sharing, etc.
* Develop annual and long-term professional goals as soon as you join the lab, and discuss them with me then and regularly thereafter. Let me know whenever yours goals change. (It's okay if your long-term goals are amorphous, just let me know.)
* Work hard and steadily, understand how you work, and let me know how I can help you work better. 
Please let me know especially if my availability, the environment, software, or hardware are slowing you down.
* Learn from your mistakes. Programming bugs, bad writing, awkward slides, undiscovered papers, are all an unfortunate part of research. Forgive yourself *and* take corrective action to reduce the error rate in the future. Of course, the optimal error rate is usually not zero... The only *real* mistakes are blowing off or ignoring what people (reviewers, coauthors, committee members, me, etc.) are telling you, ignoring data related to your research or performance, and being a jerk.  
* Perform lab service, as agreed upon (e.g., maintain the lab calendar, order office supplies, water the plants).

## Graduate researchers
I've listed below the skills I think graduate researchers should have by the time they defend their PhD. 
Your adviser and committee will help steer you, but you are in control.
(I kind of dislike the "student" convention, tbh. You're scientists, just less experienced ones.)

* *Intellectual independence and mastery*
    * Be able to define a coherent field of study, including the progress that has been made in it and the problems that remain. 
    This requires following the literature by regular, self-directed reading (at least five papers a week, conservatively, on average).
    * Have enough statistical and general knowledge to assess the strength of evidence of (almost) any study or general claim in this field.
    * Propose and carry out tractable, meaningful studies. In general, I expect graduate students to propose at least two projects or chapters for their thesis, including at least one for their thesis proposal.
    * Identify new questions you want to answer and have an idea of how to address them.
    * Have a demonstrated history of acquiring skills through self-driven instruction and self-initiated collaborations.
* *Intellectual contributions*
    * Publish at least two papers on which you're first author.
	These papers should be submitted by the time you defend. Note, this is not the requirement of relevant UChicago doctoral programs, but I think it is an important minimal target. 
    * Give talks outside the department and handle questions about your work.
    * Collaborate on projects on which you're not the first author.
    * Attend conference talks and seminars and ask questions. You should be attending most of the departmental seminars. Aim to ask at least one question at half of seminars.
* *Toughness*
    * Practice feeling clueless regularly and getting over it, especially through learning.
    * Adapt projects to deal with unexpected outcomes.
    * Learn how to handle diverse forms of criticism and professional conflict.
* *Service*
    * Be able to criticize constructively in any situation.
    * After publishing, start reviewing manuscripts for journals.
    * Understand social and political context for scientific research, including forms of entrenched discrimination and the concerns and requirements of federal funders.
    * Practice sharing your work with broader audiences, e.g., via blog posts, talks to the public, and interviews.
* Seek funding opportunities and apply for grants.
* Establish your accountability and reliability. Communicate with committees, collaborators, and administrators in a timely, respectful way, and follow through on your commitments.

Please note that you are ultimately responsible for ensuring you are meeting the requirements for your degree. The Student Advisory Committee (SAC) and later your thesis committee will help you with the planning, but you should take initiative in scheduling and planning ahead.

## Postdoctoral researchers

Generally, postdocs should have facility with all of the skills listed above. They should also 

* Develop new research projects and manage external collaborations.
* Drive projects forward in consideration of existing and ongoing research in the field.
* As negotiated, potentially take a major role in managing research performed under federal contracts, including the completion of monthly progress reports.
* Mentor junior researchers. This can be formal, but postdocs should also be providing more constructive comments across the board to other researchers, including junior ones.
* Teach selectively, if interested in a teaching position.
